kind: EgressNetworkPolicy
apiVersion: v1
metadata:
  name: my-egressfirewall
spec:
  egress:
    - type: Allow
      to:
        dnsName: www.redhat.com
    - type: Deny
      to: 
        cidrSelector: 0.0.0.0/0
