apiVersion: v1
kind: Pod
metadata:
  name: route-table-creator
spec:
  containers:
  - image: wthacr.azurecr.io/geneva:1.1
    command: ["geneva"]
    args: ["--firewall", "10.0.1.4", "--group", "jasondel-aro-rg"]
    name: geneva
    env:
      - name: AZURE_CLIENT_ID
        valueFrom:
          secretKeyRef:
            name: azure-credentials
            key: azure_client_id
      - name: AZURE_CLIENT_SECRET
        valueFrom:
          secretKeyRef:
            name: azure-credentials
            key: azure_client_secret
      - name: AZURE_TENANT_ID
        valueFrom:
          secretKeyRef:
            name: azure-credentials
            key: azure_tenant_id
      - name: AZURE_SUBSCRIPTION_ID
        valueFrom:
          secretKeyRef:
            name: azure-credentials
            key: azure_subscription_id
      - name: AZURE_REGION
        valueFrom:
          secretKeyRef:
            name: azure-credentials
            key: azure_region                        